name: 'Set Slack status and message for off hours'

# Run on Tues, Weds, Thurs at 12 noon Mountain
on: 
  schedule:
    cron: 0 18 * * 2,3,4 

jobs:
  set-slack-status:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "STATUS_EXPIRATION=$(($(date +%s) + 18000))" >> $GITHUB_ENV
      - uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          method: users.profile.set
          args: |
            { 
              "user": "${{ secrets.SLACK_USER }}",
              "profile": {
                "status_text": "Offline until 5pm Mountain",
                "status_emoji": ":outbox_tray:",
                "status_expiration": ${{ env.STATUS_EXPIRATION }}
              }
            }
      - uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          method: users.setPresence
          args: |
            {
              "user": "${{ secrets.SLACK_USER }}",
              "presence": "away"
            }
      - uses: hbfernandes/slack-action@1.0
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          args: |
            {
              "channel": "watercooler",
              "as_user": true,
              "text": ":wave: signing off til 5pm Mountain",
              "username": "matthew"
            }